SB_CONFIG_BOOTLOADER_MCUBOOT=y

# SB_CONFIG_SECURE_BOOT_NETCORE=y
# SB_CONFIG_NETCORE_APP_UPDATE=y

# SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y

SB_CONFIG_SECURE_BOOT_SIGNING_KEY_FILE="C:/project-coding/iot/projects/balancer-robot-fw/signing_key.pem"
# CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y