SB_CONFIG_BOOTLOADER_MCUBOOT=y

# ------ MCUboot Signature Verification ON ------ 
# SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="/home/royya/project-coding/iot/project/robot-balancer-fw/signing_key.pem"
# SB_CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y

# ------ MCUboot Signature Verification OFF ------ 
SB_CONFIG_BOOT_SIGNATURE_TYPE_NONE=y

# ------ MCUboot More Options ------ 
# SB_CONFIG_SECURE_BOOT_NETCORE=y
# SB_CONFIG_NETCORE_APP_UPDATE=y
# SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y